#!/bin/bash

source environment.conf

./$promethee_path/run $promethee_path/samples/harness/input/ $promethee_path/samples/harness/meta/ $promethee_path/samples/harness/output/

# depending on function_type, we can have more parameters
if [ $function_type = linear ]; then
	./$promethee_path/run -um random.tif $criterion_weight -type=$function_type -chunk=$chunk_size -ismax $p_parameter
else
	./$promethee_path/run -um random.tif $criterion_weight -type=$function_type -chunk=$chunk_size -ismax $p_parameter $q_parameter
fi

if [ -d testharness ]; then
	rm -rf testharness
fi

mkdir testharness

python $utils_path/tif-converter.py out.$test_name.tif

rm nxt.$test_name.tif
rm out.$test_name.tif

mv out.$test_name.txt testharness/
mv $promethee_path/samples/harness/output/netflow.txt testharness/

./$utils_path/comparator testharness/out.$test_name.txt testharness/netflow.txt $test_size